config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "account", path_names: {edit: 'profile'}
  #devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'signup' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
  end

  namespace :account do
    resources :dashboard, only: :index
    resources :settings, only: [:edit, :update]
    resources :calls, only: [:index, :show, :update]
    get 'settings' => 'settings#edit'
    resources :voicemails
    resources :phone_numbers
    get '/voicemails/unread', to: 'voicemails#unread'
  end

  resources :voicemails, only: :show # Public resource

  get '/*id' => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'home'
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :add_twilio_number
  before_create :stub_settings

  embeds_many :phone_numbers
  accepts_nested_attributes_for :phone_numbers

  embeds_one :setting
  accepts_nested_attributes_for :setting

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  # hack for mongo
  class << self
    def serialize_from_session(key, salt)
      record = to_adapter.get(key[0]["$oid"])
      record if record && record.authenticatable_salt == salt
    end
  end

  def after_database_authentication
    Time.zone = setting.time_zone
  end

  private
  def add_twilio_number
    number = PhoneNumber.new
    number.type = 'twilio'
    #number.
    phone_numbers.push(number)
  end

  def stub_settings
    self.setting = Setting.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    render :show
  end

  def show
    @phone_number = PhoneNumber.new
    @phone_numbers = current_user.phone_numbers
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to account_dashboard_index_path, flash: {notice: "Your settings have been updated."}
    else
      redirect_to account_dashboard_index_path, flash: {alert: "An error occured and your settings could not be updated."}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email)
  end
end

app/views/users/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Settings</h1>
  </div>
</div>


<div class="row">
  <div class="small-12 large-5 columns">
    <%= form_for(@user, url: registration_path(@user), html: { method: :put }) do |f| %>

    <div>
      <%= f.label :email, 'Account email' %>
      <%= f.text_field :email %>
    </div>

    <div>
      <%= f.label :twilio_sid, 'Twilio SID' %>
      <%= f.text_field :twilio_sid %>
    </div>

    <div>
      <%= f.label :time_zone %>
      <%= time_zone_select( "user", "time_zone", ActiveSupport::TimeZone.us_zones, {model: ActiveSupport::TimeZone, include_blank: true, default: "Pacific Time (US & Canada)"}, class: 'select2') %>
    </div>

    <label>Notification email
      <%= f.text_field :notification_email %>
      <span class="helper">Where you will receive missed call and voicemail notifications.</span>
    </label>

    <label>Blacklist enabled
      <%= f.select(:blacklist_enabled, [['Disabled', 0], ['Enabled', 1]]) %>
      <span class="helper">Block telemarketers and known bad callers from a <a href="http://www.callcap.com/products/blacklist/">maintained list</a>.</span>
    </label>


    <label>SMS forwarding
      <select name="sms_forwarding">
        <option value="1" <%#= sms_forwarding == '1' ? 'selected':nil %> >Enabled</option>
        <option value="0" <%#= sms_forwarding == '0' ? 'selected':nil %> >Disabled</option>
      </select>
    </label>

    <input type="submit" value="Update" class="button">
    <% end %>
  </div>

  <div class="small-12 large-5 columns">
    <div class="row">
      <div class="small-8 columns">
        <h4>Forwarded Numbers</h4>
      </div>
      <div class="small-4 columns">
        <p><a href="#" class="new_phone_number_link button tiny">Add new</a></p>
      </div>
    </div>

    <% if @phone_numbers.length == 0 %>
      <div data-alert class="alert-box info">
        Add some phone numbers to forward your calls to!
      </div>
    <% end %>


    <div class="new_phone_number_form_container">
      <%= render partial: '/phone_numbers/form' %>
    </div>

    <ul class="unstyled phone_numbers_container">
      <% @phone_numbers.each do |phone_number| %>
        <li>
        <%= form_for phone_number do |f| %>
            <%= f.label :number %>
            <%= f.telephone_field :number %>
            <span class="helper">Only include numbers without spaces or characters.</span>
            <br><br>
            <%= f.select(:type, [['Landline', 'landline'], ['Mobile', 'mobile'], ['Twilio', 'twilio'], ['VoIP', 'voip']]) %>
            <%= f.submit 'Update', class: 'button tiny' %>
            <%= link_to "Delete", phone_number, :method => :delete, :confirm => "Are you sure?", class: "button alert tiny" %>
        <% end %>
        </li>
      <% end %>
    </ul>
  </div>

</div>