config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "account", path_names: {edit: 'profile'}
  #devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'signup' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
  end

  namespace :account do
    resources :dashboard, only: :index
    resources :settings, only: [:edit, :update]
    resources :calls, only: [:index, :show, :update]
    get 'settings' => 'settings#edit'
    resources :voicemails
    resources :phone_numbers
    get '/voicemails/unread', to: 'voicemails#unread'
  end

  resources :voicemails, only: :show # Public resource

  get '/*id' => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'home'
end

app/models/phone_number.rb
class PhoneNumber
  include Mongoid::Document
  field :number, type: Integer
  field :type, type: String
  field :sip_host, type: String
  field :sip_username, type: String
  field :sip_password, type: String

  embedded_in :user

  def self.hasTwilioNumber(user)
    user.phone_numbers.each do |phone_number|
      return true if phone_number.type == 'twilio'
    end
    false
  end

  def self.hasForwardingNumber(user)
    user.phone_numbers.each do |phone_number|
      return true if phone_number.type != 'twilio'
    end
    false
  end
end

app/controllers/account/phone_numbers_controller.rb
class Account::PhoneNumbersController < ApplicationController
  before_action :set_phone_number, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @calls = PhoneNumber.where(user_id: current_user._id)
  end

  def create
    @phone_number = PhoneNumber.new(phone_number_params)
    current_user.phone_numbers.push(@phone_number)
    if current_user.save
      redirect_to account_settings_path, flash: {notice: 'Phone number added.'}
    else
      redirect_to account_settings_path, flash: {alert: 'Phone number failed to add.'}
    end
  end

  def update
    current_user.phone_numbers.each do |number|
      number.update_attributes(phone_number_params) if number._id.to_s == params[:id]
    end
    if current_user.save
      redirect_to account_settings_path, flash: {notice: 'Phone number updated.'}
    else
      redirect_to account_settings_path, flash: {alert: 'Phone number failed to update.'}
    end
  end

  def destroy
    @phone_number.delete
    if current_user.save
      redirect_to account_settings_path, flash: {notice: 'Phone number removed.'}
    else
      redirect_to account_settings_path, flash: {alert: 'Phone number failed to delete.'}
    end
  end

  def show
  end

  private
  def set_phone_number
    @phone_number = current_user.phone_numbers.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def phone_number_params
    params.require(:phone_number).permit(:number, :type, :sip_username, :sip_password, :sip_host)
  end
end

app/views/phone_numbers/_form.html.erb
<%= form_for @phone_number, url: account_phone_numbers_path do |f| %>

  <%= f.label :type %>
  <%= select(:phone_number, :type, [['Landline', 'landline'], ['Mobile', 'mobile'], ['Twilio', 'twilio'], ['VoIP', 'voip'], ['SIP', 'sip']]) %>

  <div class="phone_number_container">
    <%= f.label :number %>
    <%= f.telephone_field :number, placeholder: '13104567890' %>
  </div>

  <div class="sip-details">
    <%= f.label :sip_username %>
    <%= f.text_field :sip_username, placeholder: 'j_appleseed' %>

    <%= f.label :sip_password %>
    <%= f.text_field :sip_password, placeholder: 'p@$$w0rd' %>

    <%= f.label :sip_host, 'URI' %>
    <%= f.text_field :sip_host, placeholder: 'vonage.com' %>
  </div>

  <%= f.submit 'Add', class: 'button small' %>
<% end %>