config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "account", path_names: {edit: 'profile'}
  #devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'signup' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
  end

  namespace :account do
    resources :dashboard, only: :index
    resources :settings, only: [:edit, :update]
    resources :calls, only: [:index, :show, :update]
    get 'settings' => 'settings#edit'
    resources :voicemails
    resources :phone_numbers
    get '/voicemails/unread', to: 'voicemails#unread'
  end

  resources :voicemails, only: :show # Public resource

  get '/*id' => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'home'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "CopperNet" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,700italic' rel='stylesheet' type='text/css'>
  </head>

  <body class="<%= controller_name -%> <%= action_name -%>">
    <header class="contain-to-grid">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1><a href="/account/dashboard"><%= render partial: '/svg/logo_small' %></a></h1>
          </li>
           <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <li class="<%= request.path == account_settings_path ? 'active':'' %>"><%= link_to 'Settings', account_settings_path %></li>
            <li class="<%= request.path == edit_user_registration_path ? 'active':'' %>"><%= link_to 'Account', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', logout_path %></li>
            <!--
            <li class="has-dropdown">
              <a href="#">Right Button Dropdown</a>
              <ul class="dropdown">
                <li><a href="#">First link in dropdown</a></li>
              </ul>
            </li>
            -->
          </ul>

          <!-- Left Nav Section -->
          <ul class="left">
            <li class="<%= request.path == account_dashboard_index_path ? 'active':'' %>"><%= link_to 'Dashboard', account_dashboard_index_path %></li>
            <li class="<%= request.path == account_voicemails_path ? 'active':'' %>">
              <%= link_to(account_voicemails_path) do %>
                Voicemail <%= @unlistened_voicemail.count > 0 ? "(#{@unlistened_voicemail.count})" : '' %>
              <% end %>
            </li>
            <li class="<%= request.path == account_calls_path ? 'active':'' %>"><%= link_to 'Calls', account_calls_path %></li>
            <li><%= link_to 'Messages', account_dashboard_index_path %></li>
          </ul>
        </section>
      </nav>
    </header>

    <section class="row">
      <div class="small-12 columns">
        <% if notice %>
          <div data-alert class="alert-box info">
            <%= notice %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>

        <% if alert %>
          <div data-alert class="alert-box alert">
            <%= alert %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      </div>
    </section>

    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "CopperNet - Google Voice-like Application for Twilio" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,700italic' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <header class="row">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1><a href="/"><%= render partial: '/svg/logo_large' %></a></h1>
          </li>
           <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Features & Pricing', page_path('pricing') %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Return to account', account_dashboard_index_path %></li>
            <% else %>
              <!--<li><%#= link_to 'Sign up', new_user_registration_path %></li>-->
              <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
          </ul>

          <!-- Left Nav Section -->
          <ul class="left"></ul>
        </section>
      </nav>
    </header>

    <div class="row">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <%= yield %>

    <footer id="main-footer" class="row">
      <div class="small-12 columns">
        <nav>
          <ul class="inline-list centered-list">
            <li><%= link_to 'About', page_path('about') %></li>
            <li><%= link_to 'Contact', page_path('contact') %></li>
            <li><%= link_to 'Privacy Policy', page_path('privacy') %></li>
            <li><%= link_to 'Terms of Use', page_path('terms') %></li>
          </ul>
        </nav>
        <div class="copyright">
          &copy; CopperNet & <%= link_to 'Teardrop', 'http://www.teardrop.co/' %>
        </div>
      </div>
    </footer>

    <%= javascript_include_tag "application" %>
    <%= render partial: '/google_analytics/public' %>
  </body>
</html>